"""Add new field confirmed_at and confirmed_by in Booking model

Revision ID: bd73210fb476
Revises: cd5f3cc4f98b
Create Date: 2026-05-03 19:38:23.576485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd73210fb476'
down_revision: Union[str, Sequence[str], None] = 'cd5f3cc4f98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('booking', sa.Column('confirmed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'user', ['confirmed_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'confirmed_by')
    op.drop_column('booking', 'confirmed_at')
    # ### end Alembic commands ###
