"""Add new status in BookingStatus

Revision ID: cd5f3cc4f98b
Revises: adfc99d70931
Create Date: 2026-05-03 15:50:57.131918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5f3cc4f98b'
down_revision: Union[str, Sequence[str], None] = 'adfc99d70931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
